django_rest_notes/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from users.views import UserCustomViewSet
from todo.views import ProjectModelViewSet, TodoModelViewSet, test_token
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Library",
        default_version='0.1',
        description="Documentation to out project",
        contact=openapi.Contact(email="admin@admin.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

router = DefaultRouter()
router.register('users', UserCustomViewSet)
router.register('projects', ProjectModelViewSet)
router.register('todos', TodoModelViewSet)

urlpatterns = [
   # path('admin/', admin.site.urls),
   # path('api-auth/', include('rest_framework.urls')),
   # path('api/', include(router.urls), name="api"),
   # path('api-token-auth/', views.obtain_auth_token),
   # path('test_token/', test_token)

   path('admin/', admin.site.urls),
   path('api-auth/', include('rest_framework.urls')),
   path('api/', include(router.urls), name="api"),
   path('api-token-auth/', views.obtain_auth_token),
   path('test_token/', test_token),
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add, basket_remove, basket, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='product'),
]

service/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from authors.views import AuthorModelViewSet, BiographyModelViewSet, BookModelViewSet, ArticleModelViewSet, AuthorViewSimpleResp, AuthorViewSerResp
import authors.views as AuthorsViews
from authapp.views import UserModelViewSet
from mainapp.views import ArticleAPIVIew, article_view

router = DefaultRouter()
router.register('authors_model_viewset', AuthorModelViewSet)
# router.register('biography', BiographyModelViewSet)
# router.register('articles', ArticleModelViewSet)
# router.register('books', BookModelViewSet)
# router.register('article_class_view', ArticleAPIVIew)
# router.register('article_func_view', article_view)
router.register('test', AuthorsViews.AuthorViewSet,basename='test')
router.register('authors', AuthorsViews.AuthorCustomModelViewSet, basename='authors')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('views/api-view-class/', ArticleAPIVIew.as_view()),
    path('views/api-view-func/', article_view),
    path('views/testview_simple_response', AuthorViewSimpleResp.as_view()),
    path('views/testview_ser_response', AuthorViewSerResp.as_view()),
    path('views/testview_list_view', AuthorsViews.AuthorListView.as_view()),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from main.views import ProjectModelViewSet, ToDoModelViewSet
from users.views import UserModelViewSet


router = DefaultRouter()
router.register('users', UserModelViewSet)
router.register('projects', ProjectModelViewSet)
router.register('todo', ToDoModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
]

mainapp/models.py
from django.db import models
from service.settings import AUTH_USER_MODEL as User

# Create your models here.


class Article(models.Model):
    name = models.CharField(max_length=64)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

mainapp/views.py
from rest_framework.views import APIView
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer
from .models import Article
from rest_framework.response import Response

from .serializers import ArticleSerializer


class ArticleAPIVIew(APIView):
    renderer_classes = [JSONRenderer]

    def get(self, request, format=None):
        articles = Article.objects.all()
        serializer = ArticleSerializer(articles, many=True)
        return Response(serializer.data)


@api_view(['GET'])
@renderer_classes([JSONRenderer])
def article_view(request):
    articles = Article.objects.all()
    serializer = ArticleSerializer(articles, many=True)
    return Response(serializer.data)

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}

    <div class="details">
			{% include 'mainapp/includes/inc_category_menu.html' %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product text-center">
						<img src="/media/{{product.image}}">
					</div>
					<div class="slider-control d-flex ">
						<div class="block">
							<a href="#"><img src="/media/{{product.image}}" alt="" class="w-50">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{product.image}}" alt="" class="w-50">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{product.image}}" alt="" class="w-50">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> {{ product.price }} <span>руб</span></p>
					<a href="{% url 'basket:add' product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ product.description }}
					</div>
				</div>
			</div>
    </div>
{% endblock %}
	